Feature/update screens
danielsaviosec/squad-new-riders-civitas-web pull request #20
Opened 2024-11-21 13:21 UTC by annasbrama

Telas de atualizações de dados cadastrados, com extra de ajustes nas telas de cadastros.

- Uma branch para as três telas de atualizações de dados (estudante, turmas e professor);
- Todas seguindo a mesma estrutura já criada com as feitas com cadastro;
- Organização de interfaces;
- Mensagem de dados obrigatórios atualizados nas páginas de cadastro;
- Faltando somente a integração com o back.

2024-11-21 21:48 UTC, danielsaviosec requested changes

2024-11-21 21:48 UTC, danielsaviosec commented on src/app/interface/response/IClassesResponse.interface.ts
> +    id: 1,
esse id é fixo 1 por que?

2024-11-21 21:48 UTC, danielsaviosec commented on src/app/pages/main/components/student-registration/student-registration.component.ts
> +  isLoading = true;
isLoading: boolean

2024-11-21 21:48 UTC, danielsaviosec commented on src/app/pages/main/components/update-student/update-student.component.html
> +            <!-- <div class="form-card">
Por que esse código esta comentado?

2024-11-21 21:48 UTC, danielsaviosec commented on src/app/pages/main/components/update-student/update-student.component.ts
> +    const value = control.value;
faltou a tipagem dos const

2024-11-21 21:48 UTC, danielsaviosec commented on src/app/pages/main/components/update-teacher/update-teacher.component.ts
> +  isLoading = true; // Variável para controlar o carregamento
isLoading: boolean

2024-11-21 23:00 UTC, annasbrama commented on src/app/pages/main/components/update-student/update-student.component.html
> +            <!-- <div class="form-card">
É pra conseguir testar o layout da página. Senão o botão de salvar não fica ativo, pois ainda estamos dependendo desta parte do back pra liberar essa parte do código.

2024-11-22 10:34 UTC, danielsaviosec approved these changes

2024-11-22 10:34 UTC, merged